#!/bin/sh
# Creates a new journal entry. Uses $EDITOR and
# plate_md for editing and formatting. Allows 
# for markdown parsing using plate_md.
#

# Makes string url and path safe
function path_safe(){
	local path="$1"
	echo "$path" | tr ' ' '_' | tr -cd 'a-zA-Z0-9._-'
}

# (Re)loads posts MD to HTML
function load_post(){
	local post_path="$1"

	# Format the markdown into a html file
	POST_HTML_PATH="$(mktemp --suffix=.html)"
	plate_md "$post_path/body.md" "$POST_HTML_PATH"
	if [ $? -ne 0 ]; then
		echo "Failed to run plate_md"
		exit 1;
	fi

	POST_TITLE=$(cat "$post_path/.title")

	# Copy template over, replace title with post title
	# and format the given markdown into the page too.
	cat "$OUT_DIR/post_template.html" | while read line; do
		case "$line" in
			*TEMPLATE_TITLE*) echo "$POST_TITLE"    ;; # Post title
			*TEMPLATE_BODY*)  cat "$POST_HTML_PATH" ;; # Post body
			*)                echo "$line"          ;; # Other
		esac
	done > "$POST_PATH/index.html"
}

# Interactivly create post
OUT_DIR="pages"
if [ ! "$1" = "reload" ]; then
	set -x

	# Check that required plate_md is installed
	if ! command -v "plate_md"; then
		echo "plate_md is not installed."
		echo "https://github.com/x3hy/plate"
		exit 1;
	fi
	
	# Create new post directory
	read -p "Enter post title: " POST_TITLE
	
	set -xe
	POST_PATH="$OUT_DIR/"$(path_safe "$POST_TITLE")
	mkdir -p "$POST_PATH"

	# Generate timestamp and title meta files
	date -u +"%Y-%m-%dT%H:%M:%S.%3NZ" > "$POST_PATH/.time"
	echo "$POST_TITLE" > "$POST_PATH/.title"
	
	# Generate a temp MD file and open in editor
	POST_MD_PATH="$POST_PATH/body.md"
	$EDITOR "$POST_MD_PATH"
	if [ $? -ne 0 ]; then
		echo "$EDITOR returned non-zero status"
		exit 1;
	fi

	set +x

	# Load the MD to HTML
	load_post "$POST_PATH"
fi

# Reload all posts

# Load new entry into content page
cat "$OUT_DIR/source.html" | while read line; do
	case "$line" in
		*TEMPLATE_BODY*) # Content page body
			find $OUT_DIR -type d -maxdepth 1 | tail -n+2 | while read POST_PATH; do
				load_post "$POST_PATH"
				# For each post (stat config is GNU/Linux only)
				PATH_BASE="$(basename "$POST_PATH")"
				POST_TITLE=$(cat "$POST_PATH/.title")
				POST_TIME=$(cat "$POST_PATH/.time")

				# Print the html
				echo "<li>"
				echo "<a href=\"$PATH_BASE\">$PATH_BASE</a>"
				echo "- <i><span class=\"date\">$POST_TIME</span> ago</i>"
				echo "</li>"
			done
		;;
		*) echo "$line" ;; # Other
	esac
done > "$OUT_DIR/index.html"
echo "Reloaded posts"
