#!/bin/sh
# Creates a new journal entry. Uses $EDITOR and
# plate_md for editing and formatting. Allows 
# for markdown parsing using plate_md.
#

function path_safe(){
	local path="$1"
	echo "$path" | tr ' ' '_' | tr -cd 'a-zA-Z0-9._-'
}

OUT_DIR="pages"

if [ ! "$1" = "reload" ]; then
	# Check that required plate_md is installed
	if ! command -v "plate_md"; then
		echo "plate_md is not installed."
		echo "https://github.com/x3hy/plate"
		exit 1;
	fi
	
	# Create new post directory
	read -p "Enter post title: " POST_TITLE
	
	set -xe
	POST_PATH="$OUT_DIR/"$(path_safe "$POST_TITLE")
	mkdir -p "$POST_PATH"

	# Generate time
	date -u +"%Y-%m-%dT%H:%M:%S.%3NZ" > "$POST_PATH/.time"
	
	# Generate a temp MD file and open in editor
	POST_MD_PATH="$(mktemp --suffix=.md)"
	$EDITOR "$POST_MD_PATH"
	if [ $? -ne 0 ]; then
		echo "$EDITOR returned non-zero status"
		exit 1;
	fi
	
	# Format the markdown into a html file
	POST_HTML_PATH="$(mktemp --suffix=.html)"
	plate_md "$POST_MD_PATH" "$POST_HTML_PATH"
	if [ $? -ne 0 ]; then
		echo "Failed to run plate_md"
		exit 1;
	fi
	
	set +x

	# Copy template over, replace title with post title
	# and format the given markdown into the page too.
	cat post_template.html | while read line; do
		case "$line" in
			*TEMPLATE_TITLE*) echo "$POST_TITLE"    ;; # Post title
			*TEMPLATE_BODY*)  cat "$POST_HTML_PATH" ;; # Post body
			*)                echo "$line"          ;; # Other
		esac
	done > "$POST_PATH/index.html"
fi

# Load new entry into content page
cat "$OUT_DIR/source.html" | while read line; do
	case "$line" in
		*TEMPLATE_BODY*) # Content page body
			find $OUT_DIR -type d -maxdepth 1 | tail -n+2 | while read POST_PATH; do
				# For each post (stat config is GNU/Linux only)
				PATH_BASE="$(basename "$POST_PATH")"
				ISO_TIME=$(cat "$POST_PATH/.time")
				echo "<tr><td><a href=\"$PATH_BASE\">$PATH_BASE</a></td><td>$ISO_TIME</td><tr>"
			done
		;;
		*) echo "$line" ;; # Other
	esac
done > "$OUT_DIR/index.html"
