#!/bin/sh
# Loads data onto page

# Check for requirements
if ! command -v plate >/dev/null 2>&1; then
	echo "Install plate"
	exit 1;
fi

set -xe

# Load projects to page
plate -qi="source.html" \
	-I="data/repo.json" \
	-t="PLATE_PROJECTS" \
	-o="index_p.html" \
	-T='<tr><td><a href="<!--$html_url-->"><!--$name--></a></td><td class="notmobile"><mark><i><!--$description--></i></mark></td></tr>'

# Load README to page
plate -qi="index_p.html" \
	-I="data/user.json" \
	-t="PLATE_ABOUTME" \
	-o="index.html" \
	-T='<!--$readme_txt-->'

# Remove tmp files (plate has no daisy chaining)
rm index_p.html
